{{- if .Values.database.install }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apicuriodata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
{{- end }}